"""Column-for-column port of uber_clone's V1__baseline_schema.sql — same tables/columns/types,
kept as its own migration (rather than one big autogenerated migration through to the current
models.py state) so the migration history stays comparable to the Kotlin Flyway migrations and
the FastAPI sibling's Alembic revisions, one-to-one.
"""

from __future__ import annotations

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserRow",
            fields=[
                ("id", models.CharField(max_length=255, primary_key=True, serialize=False)),
                ("username", models.CharField(max_length=255, unique=True)),
                ("password_hash", models.CharField(max_length=255)),
                ("role", models.CharField(max_length=50)),
                ("avg_rating", models.FloatField(null=True)),
            ],
            options={"db_table": "users"},
        ),
        migrations.CreateModel(
            name="DriverRow",
            fields=[
                ("user_id", models.CharField(max_length=255, primary_key=True, serialize=False)),
                ("vehicle_type", models.CharField(max_length=255)),
                ("license_plate", models.CharField(max_length=255)),
                ("is_available", models.BooleanField(default=False)),
                ("avg_rating", models.FloatField(null=True)),
            ],
            options={"db_table": "drivers"},
        ),
        migrations.CreateModel(
            name="RideRow",
            fields=[
                ("id", models.CharField(max_length=255, primary_key=True, serialize=False)),
                ("rider_id", models.CharField(max_length=255)),
                ("driver_id", models.CharField(max_length=255, null=True)),
                ("pickup_lat", models.FloatField()),
                ("pickup_lng", models.FloatField()),
                ("dropoff_lat", models.FloatField()),
                ("dropoff_lng", models.FloatField()),
                ("status", models.CharField(max_length=50)),
                ("estimated_fare", models.DecimalField(decimal_places=2, max_digits=19, null=True)),
                ("fare", models.DecimalField(decimal_places=2, max_digits=19, null=True)),
                ("requested_at", models.DateTimeField()),
                ("completed_at", models.DateTimeField(null=True)),
                ("version", models.BigIntegerField(default=0)),
            ],
            options={"db_table": "rides"},
        ),
        migrations.CreateModel(
            name="RatingRow",
            fields=[
                ("id", models.CharField(max_length=255, primary_key=True, serialize=False)),
                ("ride_id", models.CharField(max_length=255)),
                ("from_user_id", models.CharField(max_length=255)),
                ("to_user_id", models.CharField(max_length=255)),
                ("score", models.IntegerField()),
                ("comment", models.TextField(null=True)),
                ("created_at", models.DateTimeField()),
            ],
            options={"db_table": "ratings"},
        ),
        migrations.AddConstraint(
            model_name="ratingrow",
            constraint=models.UniqueConstraint(
                fields=("ride_id", "from_user_id"), name="uq_ratings_ride_from"
            ),
        ),
    ]
